### ISSUE TITLE
Blocking while executing  session.channel_session().await?

### ISSUE THREAD

**Issue by TheBlindM** [bk-rs/ssh-rs#45]
Examples
```
let session = Self::create_session(&parameter).await?;
        let mut channel = session.channel_session().await?;
     
        let size = &parameter.tty_size;
        channel
            .request_pty(
                "xterm-256color",
                None,
                Option::from((
                    size.cols as u32,
                    size.rows as u32,
                    size.cols as u32,
                    size.rows as u32,
                )),
            )
            .await?;

        channel.shell().await.unwrap();
         let read = channel.stream(0);
        let write = channel.stream(0);

            .............................................

         //Use this session elsewhere
        let guard = self.session.lock().await;
       
        let mut channel = guard.channel_session().await?; // Blocking
     
        channel.exec("").await?;
        let mut mem_output = String::new();
        channel.read_to_string(&mut mem_output).await?;
        channel.wait_close().await?;
```
What would cause him to block?

**Comment by TheBlindM** [comment]
Using TokioTcpStream is no problem

**Comment by TheBlindM** [comment]
After enabling Tokio, there are always exceptions when concurrent reads and writes occur
```
thread 'tokio-runtime-worker' panicked at 'read err: Custom { kind: Other, error: "transport read" }', src\tty\ssh.rs:108:62
stack backtrace:
2023-11-23 15:39:32 - ERROR - Failure while draining incoming flow
2023-11-23 15:39:32 - ERROR - Failure while draining incoming flow
   0: std::panicking::begin_panic_handler
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\result.rs:1651
   3: enum2$<core::result::Result<usize,std::io::error::Error> >::expect<usize,std::io::error::Error>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\result.rs:1033
   4: app::tty::ssh::impl$2::readf::async_block$0::async_block$0
             at .\src\tty\ssh.rs:108
   5: core::future::future::impl$1::poll<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\future\future.rs:125
   6: tokio::runtime::task::core::impl$6::poll::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\core.rs:334
   7: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> > > > >::with_mut
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\loom\std\unsafe_cell.rs:16
   8: tokio::runtime::task::core::Core<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >::poll<core::pin::P
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\core.rs:323
   9: tokio::runtime::task::harness::poll_future::closure$0<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:485
  10: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\panic\unwind_safe.rs:271
  11: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global>
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\panicking.rs:500
  12: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::cancel_task::closure_env$0<enum2$<async_ssh2_lite::session_stream::impl_tokio::impl$0::poll_x_with::async_block_env$0<usize,async_ssh2_lite::channel::i
  13: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\panicking.rs:464
  14: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,a
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\panic.rs:142
  15: tokio::runtime::task::harness::poll_future<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:473
  16: tokio::runtime::task::harness::Harness<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >::poll_inner<
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:208
  17: tokio::runtime::task::harness::Harness<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >::poll<core::
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:153
  18: tokio::runtime::task::raw::poll<core::pin::Pin<alloc::boxed::Box<enum2$<app::tty::ssh::impl$2::readf::async_block$0::async_block_env$0>,alloc::alloc::Global> >,alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\raw.rs:276
  19: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\raw.rs:200
  20: tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >::run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\mod.rs:400
  21: tokio::runtime::scheduler::multi_thread::worker::impl$1::run_task::closure$0
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:639
  22: tokio::runtime::coop::with_budget
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\coop.rs:107
  23: tokio::runtime::coop::budget
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\coop.rs:73
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:575
  25: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:526
  26: tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure$0
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:491
  27: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0,tuple$<> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\context\scoped.rs:40
  28: tokio::runtime::context::set_scheduler::closure$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\context.rs:176
  29: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\thread\local.rs:270
  30: std::thread::local::LocalKey<tokio::runtime::context::Context>::with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>,tuple$<> >
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\thread\local.rs:246
  31: tokio::runtime::context::set_scheduler<tuple$<>,tokio::runtime::scheduler::multi_thread::worker::run::closure$0::closure_env$0>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\context.rs:176
  32: tokio::runtime::scheduler::multi_thread::worker::run::closure$0
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:486
  33: tokio::runtime::context::runtime::enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::closure_env$0,tuple$<> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\context\runtime.rs:65
  34: tokio::runtime::scheduler::multi_thread::worker::run
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:478
  35: tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure$0
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\scheduler\multi_thread\worker.rs:447
  36: tokio::runtime::blocking::task::impl$2::poll<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0,tuple$<> >
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\blocking\task.rs:42
  37: tokio::runtime::task::core::impl$6::poll::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\core.rs:334
  38: tokio::loom::std::unsafe_cell::UnsafeCell<enum2$<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0> > > >::with_mut
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\loom\std\unsafe_cell.rs:16
  39: tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task::Block
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\core.rs:323
  40: tokio::runtime::task::harness::poll_future::closure$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:485
  41: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch:
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\core\src\panic\unwind_safe.rs:271
  42: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\panicking.rs:500
  43: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$2::complete::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_e
  44: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worke
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\panicking.rs:464
  45: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,toki
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26\library\std\src\panic.rs:142
  46: tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:473
  47: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll_inner<tokio::runtime::blocking:
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:208
  48: tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>::poll<tokio::runtime::blocking::task:
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\harness.rs:153
  49: tokio::runtime::task::raw::poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::impl$0::launch::closure_env$0>,tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\raw.rs:276
  50: tokio::runtime::task::raw::RawTask::poll
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\raw.rs:200
  51: tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>::run<tokio::runtime::blocking::schedule::BlockingSchedule>
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\task\mod.rs:437
  52: tokio::runtime::blocking::pool::Task::run
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\blocking\pool.rs:159
  53: tokio::runtime::blocking::pool::Inner::run
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\blocking\pool.rs:513
  54: tokio::runtime::blocking::pool::impl$6::spawn_thread::closure$0
             at C:\Users\bangfu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.30.0\src\runtime\blocking\pool.rs:471
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by vkill** [comment]
This is a very strange usage.
```rust
let read = channel.stream(0);
let write = channel.stream(0);
```

**Comment by TheBlindM** [comment]
Previously seen examples to obtain input and output streams

**Comment by vkill** [comment]
Concurrent reading and writing should be achieved using channal.

```rust
let rw = channel.stream(0);

let (tx_write, rx_write) = mpsc::unbounded_channel::<T>();
let (tx_read, rx_read) = mpsc::unbounded_channel::<T>();

tokio::spawn(async move {
  loop {
      while let Some(x) = rx_write.recv().awiat {
        rw.write_all(x).await?;
        rw.flush().await?;
        let x = ra.read().await?;
        tx_read.send(x)?;
      }
  }
})

tx_write.send()
rx_read.recv()
```

**Comment by TheBlindM** [comment]
> Concurrent reading and writing should be achieved using channal.
> 
> ```rust
> let rw = channel.stream(0);
> 
> let (tx_write, rx_write) = mpsc::unbounded_channel::<T>();
> let (tx_read, rx_read) = mpsc::unbounded_channel::<T>();
> 
> tokio::spawn(async move {
>   loop {
>       while let Some(x) = rx_write.recv().awiat {
>         rw.write_all(x).await?;
>         rw.flush().await?;
>         let x = ra.read().await?;
>         tx_read.send(x)?;
>       }
>   }
> })
> 
> tx_write.send()
> rx_read.recv()
> ```

If we use  rw.write_all(x).await?;and ra.read().await?  together,
 how can we not obtain read without inputting, or can I execute commands like top? Is there a problem

I am currently following the following approach
```
    async fn write(&mut self, msg: String) -> Result<()> {
        let mut guard = self.write_channel.lock().await;
        // guard.write_all(msg.as_bytes()).await?;
        guard.write(msg.as_bytes()).await?;
        guard.flush().await?;
        Ok(())
    }

  async fn read(&mut self) -> Result<Receiver<Vec<u8>>> {
        let arc1 = self.read_channel.clone();
        let (tx, rx) = mpsc::channel();
        tokio::spawn(async move {
            let arc = arc1.clone();
            let mut guard2 = arc.lock().await;
            let mut buf = [0u8; 8192];
            loop {
                let bytes_read = guard2.read(&mut buf).await.expect("read err");
                unsafe {
             
                    if bytes_read != 0 {
                        tx.send((&buf[..bytes_read]).to_vec())
                            .expect("TODO: panic message");
                    }
                }
            }
        });
        Ok(rx)
    }


```

**Comment by vkill** [comment]
No matter what, it must not be used like this.
```rust
let read = channel.stream(0);
let write = channel.stream(0);
```

**Comment by vkill** [comment]
> can I execute commands like top

**Comment by vkill** [comment]
> can I execute commands like top

```rust
let mut channel = ...;
loop {
  channel.exec("top -b -n 1").await?;
  let mut s = String::new();
  channel.read_to_string(&mut s).await?;
  sleep(1s).await;
}
```

**Comment by TheBlindM** [comment]
I mean the example you gave earlier  。
this issues is OK now, thanku
